-- USERS TABLE
create table users (

  id bigint generated by default as identity primary key,

  name text,
  email text unique,
  password text,
  role text

);

-- STUDENTS TABLE
create table students (

  id bigint generated by default as identity primary key,

  name text,
  branch text,
  cgpa numeric,
  placed boolean

);

-- COMPANIES TABLE
create table companies (

  id bigint generated by default as identity primary key,

  name text,
  sector text,
  package text

);

-- JOBS TABLE
create table jobs (

  id bigint generated by default as identity primary key,

  title text,
  company text,
  deadline text

);

-- ENABLE RLS
alter table users enable row level security;
alter table students enable row level security;
alter table companies enable row level security;
alter table jobs enable row level security;

-- POLICIES
create policy "Enable all access users"
on users
for all
using (true)
with check (true);

create policy "Enable all access students"
on students
for all
using (true)
with check (true);

create policy "Enable all access companies"
on companies
for all
using (true)
with check (true);

create policy "Enable all access jobs"
on jobs
for all
using (true)
with check (true);

-- SAMPLE DATA
insert into users(name,email,password,role)
values
('Admin','admin@college.com','admin123','admin');

insert into students(name,branch,cgpa,placed)
values
('Rahul Kumar','CSE',8.5,true),
('Priya Sharma','ECE',7.9,false);

insert into companies(name,sector,package)
values
('TCS','IT','3.5 LPA'),
('Infosys','IT','4 LPA');

insert into jobs(title,company,deadline)
values
('Software Engineer','TCS','2026-06-01'),
('Data Analyst','Infosys','2026-06-15');
